version: '3'

services:
  db:
    image: postgis/postgis:12-3.2-alpine
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - "${DATABASE_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env

  backend:
    build:
      context: .
    command: sh startup.sh
    volumes:
      - .:/backend
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=todo_project.settings.dev
      - ENV=${ENV}
    depends_on:
      - db
    env_file:
      - .env

volumes:
  postgres_data: